import time
import schedule
import pandas as pd
import numpy as np
from datetime import datetime
import pytz
import sys
import os

# --- Imports ---
from Moksha_1.utils.logger import logger
from Moksha_1.config import settings
from Moksha_1.utils.messenger import messenger

# --- Agents ---
from Moksha_1.core.decision_engine import DecisionEngine       # Agent 4 (The Brain)
from Moksha_1.core.execution import ExecutionHandler          # Agent 6 (The Hands)
from Moksha_1.core.optimizer import PortfolioOptimizer        # Agent 5 (The Math)
from Moksha_1.core.risk_manager import RiskManager            # Agent 8 (The Shield)
from Moksha_1.core.regime_detector import RegimeDetector      # Agent 1 (The General)
from Moksha_1.data.storage.timescaledb import TimescaleStorage
from Moksha_1.data.ingestion.alpaca_client import AlpacaDataProvider

# --- Global Timezone ---
TZ_CENTRAL = pytz.timezone("America/Chicago")

# --- Initialize ---
try:
    logger.info("⚙️ Initializing Moksha 9.0 (Sniper) Agents...")
    
    # 1. Infrastructure
    db = TimescaleStorage()
    data_provider = AlpacaDataProvider()
    executor = ExecutionHandler() 
    
    # 2. Intelligence
    council = DecisionEngine()    
    regime_general = RegimeDetector() 
    optimizer = PortfolioOptimizer()  
    
    # 3. Safety (Connected to Live Account)
    risk_guard = RiskManager(executor.client) 
    
    logger.info("✅ All Moksha Agents Initialized Successfully.")

except Exception as e:
    logger.critical(f"❌ Failed to initialize agents: {e}", exc_info=True)
    sys.exit(1) 

def run_daily_cycle():
    logger.info(f"⏰ MARKET OPEN JOB STARTED: {datetime.now(TZ_CENTRAL)}")
    messenger.send_message("🌞 Good Morning. Starting Moksha 9.0 Sniper Cycle.", title="Moksha Wake Up")

    # 0. SAFETY CHECK: Is Market Open?
    if not executor.check_market_status():
        logger.warning("⛔ Market is Closed. Skipping Data Analysis & Execution.")
        return

    universe = settings.UNIVERSE
    logger.info(f"🌌 Trading Universe ({len(universe)} symbols)")
    
    # --- PHASE 1: MACRO ANALYSIS (Agent 1) ---
    logger.info("🏛️ Agent 1: Analyzing Market Conditions...")
    try:
        regime_data = regime_general.get_market_regime()
        market_status = regime_data.get('status', 'UNKNOWN')
        market_multiplier = regime_data.get('suggested_multiplier', 1.0)
        
        logger.info(f"🌍 Regime: {market_status}")

        # CRITICAL STOP: If Crash Mode, stop buying.
        if market_multiplier <= 0.0:
            logger.warning("⛔ CRASH DETECTED (Agent 1). Halting Buy Side.")
            messenger.send_message("⛔ CRASH DETECTED. Trading Halted.", title="Regime Alert")
            return

    except Exception as e:
        logger.error(f"❌ Agent 1 Failed: {e}")
        market_multiplier = 1.0 # Default to neutral

    # --- PHASE 2: GENERATE SIGNALS (Agent 4) ---
    try:
        logger.info("🧠 Agent 4: Analyzing Universe...")
        decisions = council.analyze_market(symbols=universe)
        
        if decisions.empty:
            logger.warning("💤 No signals generated by Neural Net. Skipping cycle.")
            return
            
        # --- SNIPER LOGIC (Moksha 9.0) ---
        # 1. Filter for Buys
        buys = decisions[decisions['final_signal'] > 0].copy()
        
        if buys.empty:
            logger.info("💤 No 'Buy' signals passed the threshold.")
            return

        # 2. Sort by Confidence (raw_signal) and Pick Top 3
        # raw_signal contains the probability from the neural net
        top_picks = buys.sort_values(by='raw_signal', ascending=False).head(3)
        active_symbols = top_picks['symbol'].tolist()
        
        logger.info(f"🎯 Sniper Selection (Top {len(active_symbols)}): {active_symbols}")
        messenger.send_message(f"Targets: {active_symbols}", title="🎯 Sniper Targets")

    except Exception as e:
        logger.error(f"❌ Agent 4 Failed: {e}")
        return

    # --- PHASE 3: OPTIMIZE & SCALE (Agent 5) ---
    logger.info(f"⚖️ Agent 5: Optimizing Weights & Volatility...")
    try:
        # Fetch History for Covariance Calculation (Last 100 days)
        history_raw = db.get_bars_df(active_symbols, limit=100)
        
        if history_raw.empty or len(history_raw) < 30:
            logger.warning("⚠️ Insufficient history for HRP. Using Equal Weight.")
            # Fallback: Equal Weight with simple Regime Multiplier
            top_picks['final_signal'] = (1.0 / len(active_symbols)) * market_multiplier
            optimized_plan = top_picks
        else:
            # Pivot data: Index=Time, Columns=Symbol, Values=Close
            history_raw['time'] = pd.to_datetime(history_raw['time'])
            history_df = history_raw.pivot(index='time', columns='symbol', values='close').sort_index()
            
            # 1. HRP Optimization (Get Base Risk-Parity Weights)
            optimized_plan = optimizer.optimize_weights(top_picks, history_df)
            
            # 2. Volatility Targeting (Moksha 9.0 Secret Sauce)
            # Calculate Portfolio Volatility (Annualized)
            returns_df = history_df.pct_change().dropna()
            cov_matrix = returns_df.cov()
            
            # Map weights to covariance matrix order
            w_map = optimized_plan.set_index('symbol')['final_signal']
            weights_vector = np.array([w_map.get(sym, 0.0) for sym in cov_matrix.index])
            
            # Variance = w.T * Cov * w
            daily_var = np.dot(np.dot(weights_vector, cov_matrix), weights_vector)
            annual_vol = np.sqrt(daily_var) * (252 ** 0.5)
            
            # Calculate Scalar
            TARGET_VOL = 0.20
            vol_scalar = 1.0
            if annual_vol > 0:
                vol_scalar = TARGET_VOL / annual_vol
                
            # Cap Leverage at 1.5x
            vol_scalar = min(vol_scalar, 1.5)
            
            logger.info(f"📊 Volatility: {annual_vol*100:.1f}% -> Target: 20% | Scalar: {vol_scalar:.2f}x")
            
            # Apply Scalar to Allocations
            optimized_plan['final_signal'] = optimized_plan['final_signal'] * vol_scalar

        # [TELEMETRY] Save Dashboard Data
        try:
            dashboard_df = optimized_plan.copy()
            dashboard_df['regime'] = market_status
            dashboard_df['timestamp'] = datetime.now().isoformat()
            if not os.path.exists("logs"): os.makedirs("logs")
            dashboard_df.to_csv("logs/latest_brain_scan.csv", index=False)
        except: pass

    except Exception as e:
        logger.error(f"⚠️ Optimization Error: {e}", exc_info=True)
        return

    # --- PHASE 4: RISK MANAGEMENT (Agent 8) ---
    logger.info("🛡️ Agent 8: Final Safety Check...")
    try:
        acct = executor.client.get_account()
        equity = float(acct.equity)
        
        safe_plan = risk_guard.validate_signals(optimized_plan, equity)
        
        if safe_plan.empty:
            logger.warning("🛡️ Risk Manager halted all trades.")
            return
            
    except Exception as e:
        logger.error(f"❌ Risk Check Failed: {e}")
        return

    # Log the final approved plan
    logger.info(f"\n--- 🚀 EXECUTING ALLOCATION ---\n{safe_plan[['symbol', 'final_signal']].to_string(index=False)}")

    # --- PHASE 5: EXECUTION (Agent 6) ---
    logger.info("⚡ Agent 6: Sending Orders...")
    try:
        # live_run=True means orders will actually go to Alpaca
        executor.execute_rebalance(safe_plan, max_allocation=1.5, live_run=True)
        messenger.send_message("✅ Rebalance Complete", title="Moksha Execution")
    except Exception as e:
        logger.critical(f"❌ Execution Failed: {e}")
        messenger.send_message(f"Execution Error: {e}", title="❌ CRITICAL")

    # --- PHASE 6: SNAPSHOT ---
    try:
        final_acct = executor.client.get_account()
        equity = float(final_acct.equity)
        cash = float(final_acct.cash)
        last_equity = float(final_acct.last_equity)
        daily_pl = equity - last_equity
        db.save_portfolio_snapshot(equity, cash, daily_pl)
        logger.info(f"📸 Snapshot Saved. Equity: ${equity:,.2f}")
    except: pass

def start_scheduler():
    logger.info("⏳ Moksha 9.0 Scheduler Started...")
    
    # Run every trading day at 08:35 AM Central (Wait 5 mins after open for data stability)
    schedule.every().day.at("08:35").do(run_daily_cycle)
    
    # Startup Check
    is_open = executor.check_market_status()
    current_hour = datetime.now(TZ_CENTRAL).hour
    
    # If market is Open AND it's early enough, run immediately
    if is_open and 8 <= current_hour <= 14:
        logger.info("⚡ Market Open. Running immediate cycle...")
        run_daily_cycle()
    else:
        logger.info(f"💤 Waiting for next scheduled run...")

    while True:
        schedule.run_pending()
        time.sleep(60)

if __name__ == "__main__":
    start_scheduler()
